language: node_js
node_js:
- 8.1.3
before_script:
- npm install
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: jaMaNvlUxCsdy4InI2cERPKVzEW5XWRy8CJxndeqCwqMjRMkwMu4XWb/3iOrp76z2Ut70QYTOVIxTO2V9BUJif7XLHxmTPwG+d9kKzOoEwAdLVGZsU0OXZvLpl9y4h2NPZgmcOLQlLrWD+2F23ITGV1wIGpUdgwFeE9lYM8bVklKkJYPrMECSCkSeavzlPDMvbO7hRwRcZpPRpkVCmicwLAF2JSVN+EnnuKO9ZabsdHIwLHYJSuBaGffEujIHnzMZXR9Zqzp3nFFnrsbEyafaCdIkqV0bABtDRJq4vUVg7x56wjJo1WESS0U99+jNYOuy17UgjoHMxVzcKX63dfRc+MMf6YYqTEGMzD2+HbxsDrXhk5YslHtvwRHoRPCqDDLdHXjLTnGe0Vm96HbvHloBx9Rsp+Pei2vCBNivwmc9nhRE8v4GdDT8tiHVRnQw/LvlVZQa3WWe1cdE1sI2qZyh/O0/uHcg3iMUuPc09hq7i/Vn2ZE2qAObRXTNC479UkbKxPeUVMAtT6o0kIdNSZ+F0nx7cHOUY2zwkRNlu0a0209JzXrN138Db5ck+psD+YlOdLSoGENSoEoXRwlnwzd6EdXiQfNaSUi+ojYDynBgzFG3gIlQCCUPwnA708PTSRpDy3kbVG1FWncpROR6CA5MLl17iDyggiY+cmKtUVhXl0=
  app: pollme-app
  on:
    repo: lfaudreejr/PollMe
before_install:
- openssl aes-256-cbc -K $encrypted_b9ecce8e6385_key -iv $encrypted_b9ecce8e6385_iv
  -in env.config.ts.enc -out ./src/app/core/env.config.ts -d
